# Generated by Django 3.2.8 on 2021-11-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insert_db', '0002_user_xxx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='xxx',
            new_name='reason',
        ),
    ]
